w10d01/lotr-demo/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  # get 'profile', controller: 'users', action: :profile
  # get 'login', to: 'users#login'

  # resources :locations

  # resources :characters

  resources :locations do
    resources :characters # /locations/:id/characters
    resources :likes # /locations/:id/likes
  end

end

w10d01/lotr-demo/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

w10d01/lotr-demo/app/models/character.rb
class Character < ApplicationRecord
  belongs_to :location # character.location
end

w10d01/lotr-demo/app/models/location.rb
class Location < ApplicationRecord
  has_many :characters # location.characters
end

w10d01/lotr-demo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

w10d01/lotr-demo/app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  def index
    # /locations/:location_id/characters
    location_id = params[:location_id] # req.params.location_id

    # find the location based on the url parameter
    @location = Location.find(location_id)

    # find only the characters associated with that location
    @characters = @location.characters

    # send the data back as JSON (instead of rendering HTML)
    render json: {
      location: @location,
      characters: @characters
    }
  end
end

w10d01/lotr-demo/app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    @locations = Location.all
  end
end

w10d01/lotr-demo/app/helpers/application_helper.rb
module ApplicationHelper
end

w10d01/lotr-demo/app/helpers/characters_helper.rb
module CharactersHelper
end

w10d01/lotr-demo/app/helpers/locations_helper.rb
module LocationsHelper
end

w10d01/lotr-demo/app/views/characters/index.html.erb
<h1>All the characters from <%= @location.name %>!</h1>

<%= link_to 'Locations', locations_path %>

<% @characters.each do |character| %>
  <div class="character">
    <h2>Name: <%= character.name %></h2>
    <h2>Poem: <%= character.poem %></h2>
    <h2>Location: <%= character.location.name %></h2>
  </div>
<% end %>

w10d01/lotr-demo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lotr</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

w10d01/lotr-demo/app/views/locations/index.html.erb
<h1>All the locations!</h1>

<% @locations.each do |location| %>
  <div class="location">
    <h2>Name: <%= location.name %></h2>
    <%= link_to 'Characters', location_characters_path(location) %>
  </div>
<% end %>